using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.Geometry;
using System;
namespace Tgirrr.CadLisp {
 internal abstract class CopySequenceTarget {
  internal string Original,Kind;internal Point3d Insertion;internal abstract void CloneAt(Transaction tr,BlockTableRecord space,Vector3d displacement,string next);
  internal static CopySequenceTarget Create(Transaction tr,ObjectId id){var e=tr.GetObject(id,OpenMode.ForRead) as Entity;if(e is DBText t)return new SimpleTarget(id,t.TextString,t.Position,"TEXT");if(e is MText mt)return new SimpleTarget(id,mt.Contents,mt.Location,"MTEXT");if(e is AttributeReference ar)return new AttributeTarget(ar.OwnerId,ar.Tag,ar.TextString,ar.Position);if(e is Dimension d){if(string.IsNullOrWhiteSpace(d.DimensionText)||d.DimensionText=="<>")throw new InvalidOperationException("Dimension phải có Text Override chứa số hoặc chữ cần tăng.");return new SimpleTarget(id,d.DimensionText,d.TextPosition,"DIMENSION");}if(e is MLeader ml){if(ml.ContentType!=ContentType.MTextContent||ml.MText==null)throw new InvalidOperationException("Multileader Block Content chưa được hỗ trợ an toàn; hãy dùng Multileader MText hoặc Attribute Block.");return new SimpleTarget(id,ml.MText.Contents,ml.TextLocation,"MULTILEADER");}throw new InvalidOperationException("Chỉ hỗ trợ TEXT, MTEXT, MULTILEADER MText, Attribute trong Block và Dimension Text Override.");}
 }
 internal sealed class SimpleTarget:CopySequenceTarget {readonly ObjectId id;internal SimpleTarget(ObjectId id,string text,Point3d point,string kind){this.id=id;Original=text;Insertion=point;Kind=kind;}internal override void CloneAt(Transaction tr,BlockTableRecord space,Vector3d move,string next){var clone=(Entity)((Entity)tr.GetObject(id,OpenMode.ForRead)).Clone();clone.TransformBy(Matrix3d.Displacement(move));if(clone is DBText t)t.TextString=next;else if(clone is MText mt)mt.Contents=next;else if(clone is Dimension d)d.DimensionText=next;else{var ml=(MLeader)clone;var text=ml.MText;text.Contents=next;ml.MText=text;}space.AppendEntity(clone);tr.AddNewlyCreatedDBObject(clone,true);}}
 internal sealed class AttributeTarget:CopySequenceTarget {readonly ObjectId blockId;readonly string tag;internal AttributeTarget(ObjectId blockId,string tag,string text,Point3d point){this.blockId=blockId;this.tag=tag;Original=text;Insertion=point;Kind="BLOCK ATTRIBUTE";}internal override void CloneAt(Transaction tr,BlockTableRecord space,Vector3d move,string next){var source=(BlockReference)tr.GetObject(blockId,OpenMode.ForRead);var clone=(BlockReference)source.Clone();clone.TransformBy(Matrix3d.Displacement(move));space.AppendEntity(clone);tr.AddNewlyCreatedDBObject(clone,true);foreach(ObjectId aid in source.AttributeCollection){var a=(AttributeReference)tr.GetObject(aid,OpenMode.ForRead);var ac=(AttributeReference)a.Clone();ac.TransformBy(Matrix3d.Displacement(move));if(string.Equals(ac.Tag,tag,StringComparison.OrdinalIgnoreCase))ac.TextString=next;clone.AttributeCollection.AppendAttribute(ac);tr.AddNewlyCreatedDBObject(ac,true);}}}
}
