using System;
using System.Globalization;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Microsoft.Win32;
namespace Tgirrr.CadLisp {
 public sealed class LinetypeWindow:Window {
  readonly TextBox name=Box("HDPE_D25"),description=Box("---HDPE DN25---"),dash=Box("15"),before=Box("2"),content=Box("HDPE D25"),style=Box("Standard"),y=Box("-1.32567"),scale=Box("2.5"),after=Box("19"),syntax=new TextBox();
  readonly CheckBox assign=new CheckBox{Content="Chuyển đối tượng dùng nét cũ sang nét mới",Foreground=Brushes.White},selectedOnly=new CheckBox{Content="Chỉ chuyển các đối tượng đang chọn",Foreground=Brushes.White};
  readonly RadioButton version=new RadioButton{Content="Tạo phiên bản mới (_V2)",IsChecked=true,Foreground=Brushes.White},overwrite=new RadioButton{Content="Ghi đè định nghĩa trong file",Foreground=Brushes.White};
  readonly Canvas preview=new Canvas{Height=100,Background=new SolidColorBrush(Color.FromRgb(27,36,48)),Margin=new Thickness(0,8,0,10)};readonly TextBlock spacingNote=new TextBlock{Foreground=new SolidColorBrush(Color.FromRgb(255,196,61)),TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,4,0,3)};string path=LinetypeService.DefaultPath,originalName="";
  static TextBox Box(string value)=>new TextBox{Text=value,Margin=new Thickness(0,2,0,6),Padding=new Thickness(6),Background=new SolidColorBrush(Color.FromRgb(50,61,75)),Foreground=Brushes.White};
  public LinetypeWindow(){Title="TGIRR — Tạo và chỉnh sửa nét vẽ";Width=780;Height=720;WindowStartupLocation=WindowStartupLocation.CenterScreen;Background=new SolidColorBrush(Color.FromRgb(36,45,57));Foreground=Brushes.White;var root=new Grid{Margin=new Thickness(18)};root.ColumnDefinitions.Add(new ColumnDefinition());root.ColumnDefinitions.Add(new ColumnDefinition());Content=root;var left=new StackPanel{Margin=new Thickness(0,0,12,0)};var right=new StackPanel{Margin=new Thickness(12,0,0,0)};Grid.SetColumn(right,1);root.Children.Add(left);root.Children.Add(right);Add(left,"Tên nét",name);Add(left,"Mô tả",description);Add(left,"Chiều dài đoạn gạch",dash);Add(left,"Khoảng trống trước chữ",before);Add(left,"Nội dung chữ",content);left.Children.Add(spacingNote);left.Children.Add(B("Áp dụng khoảng cách đẹp",ApplySpacing));Add(right,"Text Style",style);Add(right,"Độ lệch Y",y);Add(right,"Tỷ lệ chữ",scale);Add(right,"Khoảng trống sau chữ",after);foreach(var x in new UIElement[]{version,overwrite,assign,selectedOnly})right.Children.Add(x);var edit=new WrapPanel{Margin=new Thickness(0,8,0,0)};edit.Children.Add(B("Chọn nét từ file",LoadFile));edit.Children.Add(B("Chọn nét từ bản vẽ",LoadDrawing));right.Children.Add(edit);var actions=new WrapPanel();actions.Children.Add(B("Lưu thay đổi và nạp",Create));actions.Children.Add(B("Chọn file LIN",Choose));actions.Children.Add(B("Sao chép cú pháp",Copy));actions.Children.Add(B("Đóng",(s,e)=>Close()));right.Children.Add(actions);var lower=new StackPanel{Margin=new Thickness(0,400,0,0)};Grid.SetColumnSpan(lower,2);root.Children.Add(lower);lower.Children.Add(new TextBlock{Text="XEM TRƯỚC",Foreground=new SolidColorBrush(Color.FromRgb(86,190,232)),FontWeight=FontWeights.Bold});lower.Children.Add(preview);syntax.IsReadOnly=true;syntax.Height=60;syntax.TextWrapping=TextWrapping.Wrap;syntax.Background=new SolidColorBrush(Color.FromRgb(24,31,41));syntax.Foreground=Brushes.White;syntax.Padding=new Thickness(8);lower.Children.Add(syntax);foreach(var box in new[]{name,description,dash,before,content,style,y,scale,after})box.TextChanged+=(s,e)=>RefreshView();Loaded+=(s,e)=>RefreshView();}
  static void Add(Panel p,string label,UIElement field){p.Children.Add(new TextBlock{Text=label});p.Children.Add(field);}static Button B(string text,RoutedEventHandler h){var b=new Button{Content=text,Margin=new Thickness(0,5,7,2),Padding=new Thickness(9,6,9,6)};b.Click+=h;return b;}
  double N(TextBox b,string label){double v;if(!double.TryParse(b.Text.Replace(',','.'),NumberStyles.Float,CultureInfo.InvariantCulture,out v))throw new InvalidOperationException(label+" không hợp lệ.");return v;}string Def()=>LinetypeService.Definition(name.Text.Trim(),description.Text.Trim(),N(dash,"Đoạn gạch"),N(before,"Khoảng trước"),content.Text,style.Text.Trim(),N(y,"Độ lệch Y"),N(scale,"Tỷ lệ chữ"),N(after,"Khoảng sau"));
  void RefreshView(){try{var d=N(dash,"Đoạn gạch");var b=N(before,"Khoảng trước");var suggested=d+2*b;spacingNote.Text="Gợi ý khoảng cách đẹp: Khoảng sau = Đoạn gạch + 2 × Khoảng trước = "+d.ToString("0.###")+" + 2 × "+b.ToString("0.###")+" = "+suggested.ToString("0.###");syntax.Text=Def();preview.Children.Clear();var line=new System.Windows.Shapes.Line{X1=15,Y1=50,X2=700,Y2=50,Stroke=new SolidColorBrush(Color.FromRgb(75,185,226)),StrokeThickness=2,StrokeDashArray=new DoubleCollection{24,10}};preview.Children.Add(line);for(int x=110;x<650&&!string.IsNullOrWhiteSpace(content.Text);x+=190){var t=new TextBlock{Text=content.Text,Foreground=Brushes.White,Background=preview.Background,FontSize=16};Canvas.SetLeft(t,x);Canvas.SetTop(t,38);preview.Children.Add(t);}}catch{syntax.Text="Vui lòng nhập thông số hợp lệ.";spacingNote.Text="Nhập chiều dài đoạn gạch và khoảng trước để xem gợi ý.";}}
  void ApplySpacing(object s,RoutedEventArgs e){try{after.Text=(N(dash,"Đoạn gạch")+2*N(before,"Khoảng trước")).ToString("0.###",CultureInfo.InvariantCulture);}catch(Exception ex){MessageBox.Show(ex.Message,"Không thể tính khoảng cách");}}
  void Create(object s,RoutedEventArgs e){try{var doc=Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument;var requested=name.Text.Trim();var old=originalName==""?requested:originalName;var final=requested;var overwriteMode=overwrite.IsChecked==true;if(overwriteMode){if(MessageBox.Show("AutoCAD không cho nạp đè trực tiếp Linetype đang tồn tại.\n\nTool sẽ:\n1. Ghi đè định nghĩa tên gốc trong file LIN.\n2. Tạo một phiên bản mới trong bản vẽ hiện tại.\n3. Chuyển đối tượng nếu anh đã chọn tùy chọn chuyển.\n\nTiếp tục?","TGIRR",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;var originalDefinition=LinetypeService.Definition(old,description.Text.Trim(),N(dash,"Đoạn gạch"),N(before,"Khoảng trước"),content.Text,style.Text.Trim(),N(y,"Độ lệch Y"),N(scale,"Tỷ lệ chữ"),N(after,"Khoảng sau"));LinetypeService.Save(path,old,originalDefinition);final=LinetypeService.NextName(doc,old);name.Text=final;LinetypeService.Save(path,final,Def());}else{if(originalName!=""||LinetypeService.DrawingNames(doc).Any(n=>string.Equals(n,requested,StringComparison.OrdinalIgnoreCase)))final=LinetypeService.NextName(doc,originalName!=""?originalName:requested);name.Text=final;LinetypeService.Save(path,final,Def());}var moved=LinetypeService.LoadAndReplace(path,final,old,assign.IsChecked==true,selectedOnly.IsChecked==true);MessageBox.Show("Đã nạp nét mới '"+final+"'.\nĐịnh nghĩa gốc trong file: '"+old+"'.\nĐã chuyển "+moved+" đối tượng.\n\nLưu ý: AutoCAD không hỗ trợ thay nóng record cùng tên; bản vẽ hiện tại dùng '"+final+"'.","TGIRR",MessageBoxButton.OK,MessageBoxImage.Information);originalName=final;}catch(Autodesk.AutoCAD.Runtime.Exception ex){MessageBox.Show("Lỗi AutoCAD: "+ex.ErrorStatus+"\n"+ex.Message,"Không thể chỉnh sửa nét",MessageBoxButton.OK,MessageBoxImage.Error);}catch(Exception ex){MessageBox.Show(ex.Message,"Không thể chỉnh sửa nét",MessageBoxButton.OK,MessageBoxImage.Error);}}
  void ApplyDef(LinetypeDefinition d){originalName=d.Name;path=d.SourcePath;name.Text=d.Name;description.Text=d.Description;dash.Text=d.Dash.ToString(CultureInfo.InvariantCulture);before.Text=d.Before.ToString(CultureInfo.InvariantCulture);content.Text=d.Text??"";style.Text=d.Style??"Standard";y.Text=d.Y.ToString(CultureInfo.InvariantCulture);scale.Text=d.Scale.ToString(CultureInfo.InvariantCulture);after.Text=d.After.ToString(CultureInfo.InvariantCulture);RefreshView();}
  void LoadFile(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="AutoCAD Linetype (*.lin)|*.lin"};if(d.ShowDialog()==true)Pick(LinetypeService.Read(d.FileName),"Chọn nét từ file LIN");}
  void LoadDrawing(object s,RoutedEventArgs e){var doc=Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument;string typeName=null;Hide();try{var options=new Autodesk.AutoCAD.EditorInput.PromptEntityOptions("\nChọn Pline hoặc đối tượng có nét cần chỉnh sửa: ");var picked=doc.Editor.GetEntity(options);if(picked.Status!=Autodesk.AutoCAD.EditorInput.PromptStatus.OK)return;using(doc.LockDocument())using(var tr=doc.Database.TransactionManager.StartTransaction()){var entity=tr.GetObject(picked.ObjectId,Autodesk.AutoCAD.DatabaseServices.OpenMode.ForRead) as Autodesk.AutoCAD.DatabaseServices.Entity;if(entity!=null){typeName=entity.Linetype;if(typeName.Equals("ByLayer",StringComparison.OrdinalIgnoreCase)){var layers=(Autodesk.AutoCAD.DatabaseServices.LayerTable)tr.GetObject(doc.Database.LayerTableId,Autodesk.AutoCAD.DatabaseServices.OpenMode.ForRead);var layer=(Autodesk.AutoCAD.DatabaseServices.LayerTableRecord)tr.GetObject(layers[entity.Layer],Autodesk.AutoCAD.DatabaseServices.OpenMode.ForRead);var record=(Autodesk.AutoCAD.DatabaseServices.LinetypeTableRecord)tr.GetObject(layer.LinetypeObjectId,Autodesk.AutoCAD.DatabaseServices.OpenMode.ForRead);typeName=record.Name;}}}}finally{Show();Activate();}
    if(string.IsNullOrWhiteSpace(typeName)||typeName.Equals("ByBlock",StringComparison.OrdinalIgnoreCase)||typeName.Equals("Continuous",StringComparison.OrdinalIgnoreCase)){MessageBox.Show("Đối tượng không có custom Linetype để chỉnh sửa (ByBlock hoặc Continuous). Hãy chọn nét từ file LIN.","TGIRR",MessageBoxButton.OK,MessageBoxImage.Information);return;}
    var found=LinetypeService.Read(path).FirstOrDefault(x=>string.Equals(x.Name,typeName,StringComparison.OrdinalIgnoreCase));if(found==null){MessageBox.Show("Đã đọc được nét hiệu lực '"+typeName+"' nhưng không tìm thấy cú pháp trong file:\n"+path+"\n\nHãy bấm Chọn nét từ file và chọn đúng file LIN nguồn.","TGIRR",MessageBoxButton.OK,MessageBoxImage.Warning);return;}ApplyDef(found);MessageBox.Show("Đã nạp nét hiệu lực '"+typeName+"' lên form chỉnh sửa.","TGIRR");}
  void Pick(System.Collections.Generic.List<LinetypeDefinition> defs,string title){if(defs.Count==0){MessageBox.Show("Không tìm thấy định nghĩa nét phù hợp.");return;}var w=new Window{Title=title,Width=400,Height=400,Owner=this,WindowStartupLocation=WindowStartupLocation.CenterOwner};var list=new ListBox{ItemsSource=defs,DisplayMemberPath="Name",Margin=new Thickness(10)};list.MouseDoubleClick+=(s,e)=>{if(list.SelectedItem!=null){ApplyDef((LinetypeDefinition)list.SelectedItem);w.Close();}};w.Content=list;w.ShowDialog();}
  void Choose(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="AutoCAD Linetype (*.lin)|*.lin",FileName=System.IO.Path.GetFileName(path)};if(d.ShowDialog()==true)path=d.FileName;}void Copy(object s,RoutedEventArgs e){Clipboard.SetText(Def());}
 }
}
