using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.ApplicationServices;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
namespace Tgirrr.CadLisp {
 internal sealed class LinetypeDefinition { public string Name,Description,Text,Style,SourcePath;public double Dash,Before,Y,Scale,After; }
 internal static class LinetypeService {
  internal static string DefaultPath { get { var dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"TGIRR CAD LISP");Directory.CreateDirectory(dir);return Path.Combine(dir,"TGIRR_Linetypes.lin"); } }
  static double D(string v){return double.Parse(v,CultureInfo.InvariantCulture);}
  internal static string Definition(string name,string description,double dash,double before,string text,string style,double y,double scale,double after){string F(double v)=>v.ToString("0.######",CultureInfo.InvariantCulture);return "*"+name+","+description+Environment.NewLine+"A,"+F(Math.Abs(dash))+",-"+F(Math.Abs(before))+(string.IsNullOrWhiteSpace(text)?",-"+F(Math.Abs(after)):",[\""+text.Replace("\"","'")+"\","+style+",y="+F(y)+",s="+F(scale)+",u=0],-"+F(Math.Abs(after)));}
  internal static List<LinetypeDefinition> Read(string path){var result=new List<LinetypeDefinition>();if(!File.Exists(path))return result;var lines=File.ReadAllLines(path,Encoding.UTF8);for(int i=0;i<lines.Length-1;i++){if(!lines[i].TrimStart().StartsWith("*")||!lines[i+1].TrimStart().StartsWith("A,"))continue;var header=lines[i].Trim().Substring(1).Split(new[]{','},2);var body=lines[++i].Trim();try{var d=new LinetypeDefinition{Name=header[0].Trim(),Description=header.Length>1?header[1].Trim():"",Style="Standard",Scale=1,SourcePath=path};var complex=Regex.Match(body,"^A,([^,]+),([^,]+),\\[\\\"([^\\\"]*)\\\",([^,\\]]+)([^\\]]*)\\],([^,]+)$",RegexOptions.IgnoreCase);if(complex.Success){d.Dash=Math.Abs(D(complex.Groups[1].Value));d.Before=Math.Abs(D(complex.Groups[2].Value));d.Text=complex.Groups[3].Value;d.Style=complex.Groups[4].Value.Trim();var opts=complex.Groups[5].Value;var ym=Regex.Match(opts,@"y=([^,]+)",RegexOptions.IgnoreCase);var sm=Regex.Match(opts,@"s=([^,]+)",RegexOptions.IgnoreCase);d.Y=ym.Success?D(ym.Groups[1].Value):0;d.Scale=sm.Success?D(sm.Groups[1].Value):1;d.After=Math.Abs(D(complex.Groups[6].Value));}else{var p=body.Split(',');d.Dash=Math.Abs(D(p[1]));d.Before=p.Length>2?Math.Abs(D(p[2])):0;d.After=p.Length>3?Math.Abs(D(p[3])):d.Before;}result.Add(d);}catch{}}
   return result;}
  internal static void Save(string path,string name,string definition){var encoding=new UTF8Encoding(false);var old=File.Exists(path)?File.ReadAllText(path,Encoding.UTF8):"";var lines=old.Replace("\r\n","\n").Split('\n').ToList();var marker="*"+name+",";for(int i=0;i<lines.Count;i++)if(lines[i].StartsWith(marker,StringComparison.OrdinalIgnoreCase)){lines.RemoveAt(i);if(i<lines.Count&&lines[i].TrimStart().StartsWith("A,"))lines.RemoveAt(i);break;}while(lines.Count>0&&string.IsNullOrWhiteSpace(lines.Last()))lines.RemoveAt(lines.Count-1);File.WriteAllText(path,(lines.Count>0?string.Join(Environment.NewLine,lines)+Environment.NewLine:"")+definition+Environment.NewLine,encoding);}
  internal static List<string> DrawingNames(Document doc){return DrawingNamesAll(doc).Where(n=>n!="ByLayer"&&n!="ByBlock"&&n!="Continuous").ToList();}
  internal static List<string> DrawingNamesAll(Document doc){using(doc.LockDocument())using(var tr=doc.TransactionManager.StartTransaction()){var table=(LinetypeTable)tr.GetObject(doc.Database.LinetypeTableId,OpenMode.ForRead);return table.Cast<Autodesk.AutoCAD.DatabaseServices.ObjectId>().Select(id=>((LinetypeTableRecord)tr.GetObject(id,OpenMode.ForRead)).Name).OrderBy(n=>n).ToList();}}
  internal static void LoadAll(string path){var doc=Application.DocumentManager.MdiActiveDocument;var definitions=Read(path);if(definitions.Count==0)throw new InvalidOperationException("File LIN không có định nghĩa được hỗ trợ.");using(doc.LockDocument()){foreach(var definition in definitions){try{doc.Database.LoadLineTypeFile(definition.Name,path);}catch(Autodesk.AutoCAD.Runtime.Exception ex){if(ex.ErrorStatus!=Autodesk.AutoCAD.Runtime.ErrorStatus.DuplicateRecordName)throw;}}}}
  internal static string NextName(Document doc,string desired){using(doc.LockDocument())using(var tr=doc.TransactionManager.StartTransaction()){var table=(LinetypeTable)tr.GetObject(doc.Database.LinetypeTableId,OpenMode.ForRead);if(!table.Has(desired))return desired;for(int i=2;i<1000;i++){var n=desired+"_V"+i;if(!table.Has(n))return n;}throw new InvalidOperationException("Không thể tạo tên phiên bản mới.");}}
  internal static int LoadAndReplace(string path,string name,string oldName,bool replace,bool selectedOnly){var doc=Application.DocumentManager.MdiActiveDocument;var db=doc.Database;using(doc.LockDocument()){db.LoadLineTypeFile(name,path);if(!replace)return 0;Autodesk.AutoCAD.DatabaseServices.ObjectId[] ids;if(selectedOnly){var s=doc.Editor.SelectImplied();ids=s.Status==Autodesk.AutoCAD.EditorInput.PromptStatus.OK?s.Value.GetObjectIds():new Autodesk.AutoCAD.DatabaseServices.ObjectId[0];}else{using(var tr0=db.TransactionManager.StartTransaction()){var blocks=(BlockTable)tr0.GetObject(db.BlockTableId,OpenMode.ForRead);var all=new List<Autodesk.AutoCAD.DatabaseServices.ObjectId>();foreach(var bid in blocks){var btr=(BlockTableRecord)tr0.GetObject(bid,OpenMode.ForRead);if(btr.IsLayout)all.AddRange(btr.Cast<Autodesk.AutoCAD.DatabaseServices.ObjectId>());}ids=all.ToArray();}}
    int count=0;using(var tr=db.TransactionManager.StartTransaction()){foreach(var id in ids){var e=tr.GetObject(id,OpenMode.ForRead,false) as Entity;if(e!=null&&string.Equals(e.Linetype,oldName,StringComparison.OrdinalIgnoreCase)){e.UpgradeOpen();e.Linetype=name;count++;}}tr.Commit();}return count;}}
 }
}
